"""
PowerPoint Generation Service - Create presentations using python-pptx
"""
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from typing import List, Dict
import os
from datetime import datetime

class PPTService:
    def __init__(self):
        """Initialize PowerPoint service"""
        self.output_dir = "generated_presentations"
        os.makedirs(self.output_dir, exist_ok=True)
        print("[PPTService] Initialized")
    
    def create_presentation(self, title: str, slides_content: List[Dict], template: str = "modern") -> Dict:
        """
        Create a PowerPoint presentation
        
        slides_content format:
        [
            {"title": "Slide Title", "content": ["Point 1", "Point 2"]},
            {"title": "Another Slide", "content": ["Content here"]}
        ]
        """
        try:
            # Create presentation
            prs = Presentation()
            prs.slide_width = Inches(10)
            prs.slide_height = Inches(7.5)
            
            # Title slide
            self._add_title_slide(prs, title, template)
            
            # Content slides
            for slide_data in slides_content:
                self._add_content_slide(prs, slide_data, template)
            
            # Save presentation
            filename = f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
            filepath = os.path.join(self.output_dir, filename)
            prs.save(filepath)
            
            return {
                "success": True,
                "filename": filename,
                "filepath": filepath,
                "slides_count": len(prs.slides)
            }
            
        except Exception as e:
            print(f"[PPTService] Error: {e}")
            return {"success": False, "error": str(e)}
    
    def _add_title_slide(self, prs, title: str, template: str):
        """Add title slide"""
        slide_layout = prs.slide_layouts[0]  # Title slide layout
        slide = prs.slides.add_slide(slide_layout)
        
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        
        title_shape.text = title
        subtitle_shape.text = f"Generated by JARVIS AI\n{datetime.now().strftime('%B %d, %Y')}"
        
        # Apply styling
        if template == "modern":
            self._apply_modern_style(title_shape)
    
    def _add_content_slide(self, prs, slide_data: Dict, template: str):
        """Add content slide"""
        slide_layout = prs.slide_layouts[1]  # Title and content layout
        slide = prs.slides.add_slide(slide_layout)
        
        title_shape = slide.shapes.title
        content_shape = slide.placeholders[1]
        
        title_shape.text = slide_data.get("title", "")
        
        # Add bullet points
        text_frame = content_shape.text_frame
        text_frame.clear()
        
        content = slide_data.get("content", [])
        if isinstance(content, str):
            content = [content]
        
        for i, point in enumerate(content):
            if i == 0:
                p = text_frame.paragraphs[0]
            else:
                p = text_frame.add_paragraph()
            
            p.text = point
            p.level = 0
            
            # Styling
            if template == "modern":
                p.font.size = Pt(18)
                p.font.name = 'Arial'
    
    def _apply_modern_style(self, shape):
        """Apply modern styling to shape"""
        text_frame = shape.text_frame
        for paragraph in text_frame.paragraphs:
            paragraph.font.bold = True
            paragraph.font.size = Pt(44)
            paragraph.font.color.rgb = RGBColor(0, 112, 192)
    
    def create_from_text(self, text: str, title: str = "Presentation") -> Dict:
        """Create presentation from plain text (auto-split into slides)"""
        try:
            # Split text into slides (by double newline or numbered points)
            slides_content = []
            
            # Simple split by paragraphs
            paragraphs = [p.strip() for p in text.split('\n\n') if p.strip()]
            
            for i, para in enumerate(paragraphs):
                slide_title = f"Slide {i+1}"
                
                # Check if paragraph has a title (first line ends with :)
                lines = para.split('\n')
                if len(lines) > 1 and lines[0].endswith(':'):
                    slide_title = lines[0][:-1]
                    content = lines[1:]
                else:
                    content = lines
                
                slides_content.append({
                    "title": slide_title,
                    "content": content
                })
            
            return self.create_presentation(title, slides_content)
            
        except Exception as e:
            return {"success": False, "error": str(e)}
